columns:        ['user',  'whiskey',  'rating']
columns_types:  ['token', 'token',    'float']
sep:            '\t'

dir_whiskey_dataset:        '/opt/ml/workspace/RecBole/dataset/whiskey'
dir_inter:                  '/opt/ml/workspace/RecBole/dataset/whiskey/whiskey.inter'
dir_Pop:                    '/opt/ml/workspace/RecBole/dataset/whiskey/Pop.csv'
dir_model_saved:            '/opt/ml/workspace/RecBole/model_saved'
dir_Top_1000_Whiskey_Data:  '/opt/ml/workspace/src/Top_1000_Whiskey_Data.csv'
dir_whiskey_cluster:        '/opt/ml/workspace/src/whiskey_cluster.csv'
dir_whiskey_w_tag:          '/opt/ml/workspace/src/whisky_w_tags.csv'

file_model_used:            'LightGCN-May-20-2022_05-21-45.pth'
file_model_vae_used:        'RecVAE-May-20-2022_05-03-35.pth'

won_per_cad: 984.52
sort_by: ['Meta Critic', '#']